services:
  db:
    image: mariadb
    container_name: mariadb_container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: insurance_app
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - app_network

volumes:
  db_data:
    external: true

networks:
  app_network:
    driver: bridge

