version: '3.8'

services:
  db:
    image: mariadb
    container_name: mariadb_container_eshop_app
    ports:
      - "3308:3306"  # Externý port 3308 na interný port 3306
    environment:
      MARIADB_ROOT_PASSWORD: root  # Pridajte heslo pre root
      MYSQL_DATABASE: eshop_app
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network  # Pripojiť kontajner k sieti

  phpmyadmin:
    image: phpmyadmin
    container_name: custom_phpmyadmin_container
    ports:
      - "8083:80"  # Externý port 8082 na interný port 80
    environment:
      PMA_HOST: db  # Názov služby databázy v rámci siete
      PMA_PORT: 3306  # Určenie správneho portu na pripojenie k db
    networks:
      - app_network  # Pripojiť kontajner k sieti

volumes:
  db_data:

networks:
  app_network:
    driver: bridge

